{{- if .Values.operator.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "structural-worker-autoscaler.rbac.roleKind" . }}
metadata:
  name: {{ include "structural-worker-autoscaler.rbac.name" . }}
  {{- if eq .Values.operator.configuration.scope "namespace" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - create
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - structural.tonic.ai
  resources:
  - structuralworkerpools
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - structural.tonic.ai
  resources:
  - structuralworkerpools/status
  verbs:
  - get
  - update
  - patch
{{- end }}