{
 "title": "Structural Worker Pool",
 "description": "Provides insights into Structural worker autoscaling",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "operator_name",
    "label": "Operator",
    "query": {
     "query": "label_values(tonic_ai_structural_workerpool_operator_info,operator_name)"
    }
   },
   {
    "name": "pool_ns",
    "label": "Namespace",
    "query": {
     "query": "label_values(tonic_ai_structural_workerpool_pool_info{pool_managed_by=\"$operator_name\"},pool_namespace)"
    }
   },
   {
    "name": "pool_name",
    "label": "Pool Name",
    "query": {
     "query": "label_values(tonic_ai_structural_workerpool_pool_info{pool_namespace=\"$pool_ns\", pool_managed_by=\"$operator_name\"},pool_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "tonic_ai_structural_workerpool_operator_info{operator_name=\"${operator_name}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operator CPU Usage (# of cores)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Core" } },
   "targets": [
    {
     "expr": "tonic_ai_structural_workerpool_operator_info{operator_name=\"${operator_name}\"} \n* on(pod, namespace) group_left()\nsum(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__interval])) by (pod, namespace)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Operator CPU Usage (% of limit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "tonic_ai_structural_workerpool_operator_info{operator_name=\"${operator_name}\"} \n* on(pod, namespace) group_left()\n(\n  sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__interval])) by (pod, namespace) / \n  sum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (pod, namespace)\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Operator Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tonic_ai_structural_workerpool_operator_info{operator_name=\"${operator_name}\"} \n* on(pod, namespace) group_left()\nsum (container_memory_working_set_bytes{image!=\"\"}) by(pod, namespace) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Operator Memory Usage (% of limit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "tonic_ai_structural_workerpool_operator_info{operator_name=\"${operator_name}\"} \n* on(pod, namespace) group_left()\n(\n  sum by (pod, namespace) (container_memory_working_set_bytes{image!=\"\"})\n  / \n  sum by (pod, namespace) (kube_pod_container_resource_limits{resource=\"memory\"})\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Worker Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Worker Pools",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\"}) by (pool_managed_by)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(tonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\", pool_status=\"Active\"}) by (pool_managed_by)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(tonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\", pool_status=\"Paused\"}) by (pool_managed_by)",
     "legendFormat": "Paused"
    },
    {
     "expr": "sum(tonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\", pool_status=\"Shutdown\"}) by (pool_managed_by)",
     "legendFormat": "Shutdown"
    }
   ]
  },
  {
   "title": "Worker Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(tonic_ai_structural_workerpool_running_workers{}) by(pool_name, pool_namespace) * on(pool_name, pool_namespace) group_right()\ntonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\"})\n+\nsum(max(tonic_ai_structural_workerpool_failed_workers{}) by(pool_name, pool_namespace) * on(pool_name, pool_namespace) group_right()\ntonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\"})\n+\nsum(max(tonic_ai_structural_workerpool_pending_workers{}) by(pool_name, pool_namespace) * on(pool_name, pool_namespace) group_right()\ntonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(max(tonic_ai_structural_workerpool_running_workers{}) by(pool_name, pool_namespace) * on(pool_name, pool_namespace) group_right()\ntonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\"})\n",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(max(tonic_ai_structural_workerpool_pending_workers{}) by(pool_name, pool_namespace) * on(pool_name, pool_namespace) group_right()\ntonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(max(tonic_ai_structural_workerpool_failed_workers{}) by(pool_name, pool_namespace) * on(pool_name, pool_namespace) group_right()\ntonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Total Worker Memory Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n      max by (pool_name, pool_namespace) (\n        tonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\"}\n      )\n    * on (pool_name, pool_namespace) group_right ()\n    max by (pod, namespace, pool_name, pool_namespace) (\n      label_replace(\n        label_replace(tonic_ai_structural_workerpool_pool_worker_pod_info, \"pod\", \"$1\", \"pod_name\", \"(.*)\"),\n        \"namespace\",\n        \"$1\",\n        \"pod_namespace\",\n        \"(.*)\"\n      ))\n  * on (pod, namespace) group_right (pool_name, pool_namespace)\n    container_memory_working_set_bytes{image!=\"\"}\n) by (pool_name, pool_namespace)",
     "legendFormat": "{{pool_namespace}}/{{pool_name}}"
    }
   ]
  },
  {
   "title": "Total Worker CPU Usage (# Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum(\n      max by (pool_name, pool_namespace) (\n        tonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\"}\n      )\n    * on (pool_name, pool_namespace) group_right ()\n    max by (pod, namespace, pool_name, pool_namespace) (\n      label_replace(\n        label_replace(tonic_ai_structural_workerpool_pool_worker_pod_info, \"pod\", \"$1\", \"pod_name\", \"(.*)\"),\n        \"namespace\",\n        \"$1\",\n        \"pod_namespace\",\n        \"(.*)\"\n      ))\n  * on (pod, namespace) group_right (pool_name, pool_namespace)\n    sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__interval])) by (pod, namespace)\n) by (pool_name, pool_namespace)",
     "legendFormat": "{{pool_namespace}}/{{pool_name}}"
    }
   ]
  },
  {
   "title": "Generation Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(\n  max (tonic_ai_structural_workerpool_generation_queue_size{}) by (pool_name, pool_namespace)\n  * on(pool_name, pool_namespace) group_right()\n  tonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\"}\n) by (pool_name, pool_namespace)",
     "legendFormat": "{{pool_namespace}}/{{pool_name}}"
    }
   ]
  },
  { "title": "Worker Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Periods With Queued Work",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "max by (pool_name, pool_namespace) (tonic_ai_structural_workerpool_generation_queue_size{\n    pool_name=\"${pool_name}\",\n    pool_namespace=\"${pool_ns}\"\n}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generation Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "max by (pool_name, pool_namespace) (tonic_ai_structural_workerpool_generation_queue_size{\n    pool_name=\"${pool_name}\",  \n    pool_namespace=\"${pool_ns}\"\n})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Pods",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (pool_name, pool_namespace) (tonic_ai_structural_workerpool_total_pool_capacity{    pool_name=\"${pool_name}\",  \n    pool_namespace=\"${pool_ns}\"})\n-\nmax by (pool_name, pool_namespace) (tonic_ai_structural_workerpool_current_pool_capacity{    pool_name=\"${pool_name}\",  \n    pool_namespace=\"${pool_ns}\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "max by (pool_name, pool_namespace) (tonic_ai_structural_workerpool_running_workers{    pool_name=\"${pool_name}\",  \n    pool_namespace=\"${pool_ns}\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "max by (pool_name, pool_namespace) (tonic_ai_structural_workerpool_pending_workers{    pool_name=\"${pool_name}\",  \n    pool_namespace=\"${pool_ns}\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max by (pool_name, pool_namespace) (tonic_ai_structural_workerpool_failed_workers{    pool_name=\"${pool_name}\",  \n    pool_namespace=\"${pool_ns}\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Worker Pool Capacity",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pool_name, pool_namespace) (tonic_ai_structural_workerpool_total_pool_capacity{pool_name=\"${pool_name}\", pool_namespace=\"${pool_ns}\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "max by (pool_name, pool_namespace) (tonic_ai_structural_workerpool_current_pool_capacity{    pool_name=\"${pool_name}\",  \n    pool_namespace=\"${pool_ns}\"})",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Worker Memory Usage (% of limit)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n      max by (pool_name, pool_namespace) (\n        tonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\"}\n      )\n    * on (pool_name, pool_namespace) group_right ()\n    max by (pod, namespace, pool_name, pool_namespace) (\n      label_replace(\n        label_replace(tonic_ai_structural_workerpool_pool_worker_pod_info, \"pod\", \"$1\", \"pod_name\", \"(.*)\"),\n        \"namespace\",\n        \"$1\",\n        \"pod_namespace\",\n        \"(.*)\"\n      ))\n  * on (pod, namespace) group_right (pool_name, pool_namespace)\n    container_memory_working_set_bytes{image!=\"\"}\n) by (pod, namespace)\n/\nsum (kube_pod_container_resource_limits{resource=\"memory\"}) by (pod, namespace)",
     "legendFormat": "{{pod}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Worker Memory Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n      max by (pool_name, pool_namespace) (\n        tonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\"}\n      )\n    * on (pool_name, pool_namespace) group_right ()\n    max by (pod, namespace, pool_name, pool_namespace) (\n      label_replace(\n        label_replace(tonic_ai_structural_workerpool_pool_worker_pod_info, \"pod\", \"$1\", \"pod_name\", \"(.*)\"),\n        \"namespace\",\n        \"$1\",\n        \"pod_namespace\",\n        \"(.*)\"\n      ))\n  * on (pod, namespace) group_right (pool_name, pool_namespace)\n        container_memory_working_set_bytes{image!=\"\"}\n) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker CPU Usage (% of limit)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n      max by (pool_name, pool_namespace) (\n        tonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\"}\n      )\n    * on (pool_name, pool_namespace) group_right ()\n    max by (pod, namespace, pool_name, pool_namespace) (\n      label_replace(\n        label_replace(tonic_ai_structural_workerpool_pool_worker_pod_info, \"pod\", \"$1\", \"pod_name\", \"(.*)\"),\n        \"namespace\",\n        \"$1\",\n        \"pod_namespace\",\n        \"(.*)\"\n      ))\n  * on (pod, namespace) group_right (pool_name, pool_namespace)\n  sum by (pod, namespace) (rate(container_cpu_usage_seconds_total{image!=\"\"}[$__interval]))\n) by (pod, namespace)\n/\n  sum by (pod, namespace) (kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Worker CPU Usage (# of cores)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "Core" } },
   "targets": [
    {
     "expr": "sum(\n      max by (pool_name, pool_namespace) (\n        tonic_ai_structural_workerpool_pool_info{pool_managed_by=\"${operator_name}\"}\n      )\n    * on (pool_name, pool_namespace) group_right ()\n    max by (pod, namespace, pool_name, pool_namespace) (\n      label_replace(\n        label_replace(tonic_ai_structural_workerpool_pool_worker_pod_info, \"pod\", \"$1\", \"pod_name\", \"(.*)\"),\n        \"namespace\",\n        \"$1\",\n        \"pod_namespace\",\n        \"(.*)\"\n      ))\n  * on (pod, namespace) group_right (pool_name, pool_namespace)\n    sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__interval])) by (pod, namespace)\n) by (pod)",
     "legendFormat": "{{pod}}"
    },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}